language: cpp
compiler: gcc

install:
  - sudo pip install cpplint

script: 
  - cpplint --filter=-[whitespace/braces] ./Lesson1/app/main.c ./Lesson3/app/main.c ./Lesson4/app/main.c  

after_success:
  - echo "Success"
  
after_failure:
  - cat oclint.log
